### PR TITLE
fix(Viewer): Expose picked values via click subscription

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@thewtex There's no other subscription management functionality in the store, but I put this one there so we would have it available to any of our components, as well as making it available to embedding applications.  Let me know if a cleaner approach comes to mind.

**Comment by oeway** [comment]
Nice! I am thinking that would a even more generic event bus make sense? The viewer can expose a standard [EventEmitter](https://github.com/EventEmitter2/EventEmitter2/blob/master/README.md) interface(with functions including on, once, off, emit etc.), one can subscribe to many different events. Not only pick value, but also view change, camera position change etc.

**Comment by thewtex** [comment]
@scottwittenburg nice!

@oeway thanks for the suggestion! 

@scottwittenburg could you please look into providing subscriptions and exposing the `EventEmitter` interface via the `eventemitter2` package?

**Comment by scottwittenburg** [comment]
> @scottwittenburg could you please look into providing subscriptions and exposing the `EventEmitter` interface via the `eventemitter2` package?

Yes, will do. 👍

**Comment by thewtex** [comment]
I noticed `eventemitter3` is available -- I am guessing it is better than `eventemitter2` ;-).

https://www.npmjs.com/package/eventemitter3

**Comment by thewtex** [comment]
Required API's for Juptyer

- [ ] `publicAPI.setLabelMap`

**Comment by thewtex** [comment]
Superceded by #289

**Pull request closed without merging**
