### PR TITLE
ci(GraphicalTests): Re-enable

### PR DESCRIPTION
**Pull request by thewtex**
Tests were failing with false positives due to Firefox 75. Firefox 76 is
now out.

### CODE REVIEW

**Comment by thewtex** [comment]
Closes #260

**Comment by thewtex** [comment]
@floryst running into

```
> karma start ./karma.conf.js --browsers Chrome,Firefox "--browsers" "Firefox"

sh: 1: karma: not found
```

but just for Node 12. Does this ring a bell? :bell: :sound:

**Comment by floryst** [comment]
Yeah, that's due to [needle having issues right now with last node 12 version](https://github.com/tomas/needle/issues/312). You can install `request` as a dev dependency as a workaround.

**Comment by thewtex** [comment]
@floryst :1st_place_medal: thanks!

**Pull request merged**
