### PR TITLE
Multi scale

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by oeway** [comment]
This is awesome! Looking forward to it.

**Comment by oeway** [comment]
Just for curiosity, can we feed a zarr store interface with `getItem` into the viewer. With imjoy-rpc, the zarr store interface can basically implemented in Python, just like zarr.js and vizarr does [example](https://colab.research.google.com/github/hms-dbmi/vizarr/blob/master/example/mandelbrot.ipynb)?

**Comment by thewtex** [comment]
> Just for curiosity, can we feed a zarr store interface with getItem into the viewer. With imjoy-rpc, the zarr store interface can basically implemented in Python, just like zarr.js and vizarr does example?

@oeway to have access to the chunking interface, we will be able to provide a zarr interface that has a JavaScript implementation or a zarr interface that talks to an ImJoy-Python plugin. This is for performance.

**Comment by thewtex** [comment]
@oeway a lot of refactoring in this branch, looking ahead to better kaibu integration...

Also fleshing out the ImJoy-Plugin API (now exported from the bundle). I would appreciate your feedback after it is ready.

**Comment by oeway** [comment]
Wow, great features in the making! You even added layers support, cool!

**Comment by thewtex** [comment]
@oeway yes, great suggestions -- getting around to them :-)

**Comment by thewtex** [comment]
@oeway thank you for your patience! There are a number of fundamental improvements here. Of course, this gigantic branch is difficult to review. There is more to do -- looking forward to your feedback! I will follow up on issues.

**Pull request merged**
