### PR TITLE
feat(CornerAnnotation): Move corner annotation SE -> NE

### PR DESCRIPTION
**Pull request by bnmajor**
So that is is not blocked by the plane sliders in smaller views

Old:
annotations_se

New:
annotations_ne

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
LGTM!

**Comment by aylward** [comment]
Nice!!!

**Review by aylward — APPROVED** [review]

**Review by PaulHax — APPROVED** [review]
LGTM

**Comment by bnmajor** [comment]
@thewtex Thanks!

**Pull request merged**
