### PR TITLE
feat(ImJoy): Support setPointSets

### PR DESCRIPTION
**Pull request by oeway**
This PR allows displaying point cloud with the ImJoy API.

Fixes https://github.com/Kitware/itk-vtk-viewer/issues/407

### CODE REVIEW

**Comment by oeway** [comment]
@thewtex One of the tests is failing and I have no idea how to fix it. Please take a look.

**Comment by thewtex** [comment]
@oeway awesome work!! 🌟 ☁️ 🌻 

>@thewtex One of the tests is failing and I have no idea how to fix it. Please take a look.

We just have to bump the expected number of tests from `5` to `6` here:

https://github.com/Kitware/itk-vtk-viewer/blob/718ad2b482f2a30ee5556b24f45cc5c18b7a8348/test/imjoyTest.js#L53

>Another question is about the Plane Index Slider, how do we disable that for pointSets?

In progress, but the planes will be used to clip the point sets so you can interactively "look" into them.

**Comment by oeway** [comment]
Thank you!

I see! I tried the plane index slider, it doesn’t seem to have any effect.
In any case it might be good to provide a function to disable it.

**Comment by oeway** [comment]
@thewtex I would like to display several pint sets, and I am wondering how we can specify the color for each set.

**Pull request merged**
