### PR TITLE
fix(createGeometryColorChooser): Default geometry color is red

### PR DESCRIPTION
**Pull request by thewtex**
Has a good contrast with the viridis colormap used for images.

### CODE REVIEW

**Comment by kerautret** [comment]
Thanks a lot that works perfectly ;) 👍🏻

Capture d’écran 2020-04-26 à 10 51 15

**Comment by kerautret** [comment]
Perhaps the same edit can be done for the alpha selection ? For general use the default value can be let to 1.0 but it could a way to change it in a custom version.
https://github.com/Kitware/itk-vtk-viewer/blob/master/src/UserInterface/Geometries/createGeometryOpacitySlider.js

**Comment by thewtex** [comment]
> Perhaps the same edit can be done for the alpha selection ? For general use the default value can be let to 1.0 but it could a way to change it in a custom version.
https://github.com/Kitware/itk-vtk-viewer/blob/master/src/UserInterface/Geometries/createGeometryOpacitySlider.js

Yes, could you please create a PR?

**Comment by kerautret** [comment]
> > Perhaps the same edit can be done for the alpha selection ? For general use the default value can be let to 1.0 but it could a way to change it in a custom version.
> > https://github.com/Kitware/itk-vtk-viewer/blob/master/src/UserInterface/Geometries/createGeometryOpacitySlider.js
> 
> Yes, could you please create a PR?

Yes I do it :) Thanks for this new version

**Pull request merged**
