### PR TITLE
Default colormap

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
@aylward thanks for the suggestion!

It turns out that CT-Chest-Vessels is similar to CT-AAA, but more linear and with better contrast, so going with for better universality.

**Comment by bnmajor** [comment]
Looks really nice! I am seeing that that colormap selector does not seem to accurately reflect the new default though
cmap_dropdown_bug

**Comment by thewtex** [comment]
@bnmajor thanks for testing! Did you `npm ci` locally before building? There are new packages that may be missing for the UI colormaps.

**Comment by thewtex** [comment]
@bnmajor also `npm run build` or `npm run build:ui` to build the UI package :-)

**Review by bnmajor — APPROVED** [review]
@thewtex my mistake - I was using the boostrap-ui without thinking! The reference-ui looks great!

**Review by PaulHax — APPROVED** [review]
LGTM!

**Pull request merged**
