### PR TITLE
fix(Viewer): Make labelmap component proportional in volume rendering

### PR DESCRIPTION
**Pull request by scottwittenburg**
Needs this [change](https://github.com/Kitware/vtk-js/pull/1434) from `vtk.js`.

proportional-component-optimize

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@thewtex This is still missing that extra multiplier you described, and isn't tested other than with the zarr-ized ccf.  So let's iterate on it a bit before we decide?

**Comment by scottwittenburg** [comment]
@thewtex I couldn't get everything done tonight, but here's a video showing the latest:

per-label-weighting

**Comment by thewtex** [comment]
@scottwittenburg I am going to start integrating at least the click selection functionality into Jupyter -- would you please factor out the *clickCallback* improvements here into a separate commit that can be merged while working out the opacity details? In the process it would be best to have a *subscribe* interface so we can have two callbacks registered -- updating the selected label map and sending the last clicked data down to Python.

**Comment by scottwittenburg** [comment]
@thewtex I think this is ready for review.  As it turned out, enhancing the label `select` wasn't easy and straightforward, so I wanted to defer that until we come up with a better UI for managing those per-label weights.  I think I addressed the other items we discussed friday.

Next PR will update the event subscription infrastructure and expose the API we'll need to embed the viewer as a value widget in a Jupyter notebook.

**Pull request merged**
