### PR TITLE
feat(itkVtkViewProxy): add touch camera manipulator

### PR DESCRIPTION
**Pull request by idoRosen25**
add gesture manipulator to viewer.

fixing gesture event features on viewer.

### CODE REVIEW

**Review by PaulHax — CHANGES_REQUESTED** [review]
Feels great!  Thank you.  3 small requests:

Can you move changes to the itkVtkViewProxy.js file? 
 Perhaps around here:
 https://github.com/Kitware/itk-vtk-viewer/blob/250144afac61779a9bd1fc461aedeb60b8090b7c/src/Rendering/VTKJS/vtk/ItkVtkViewProxy.js#L431

An insert something like this
```
const gestureManipulator = vtkGestureCameraManipulator.newInstance({
    pinchEnabled: true,
    rotateEnabled: true,
    panEnabled: true,
  })
model.interactorStyle2D.addGestureManipulator(gestureManipulator)
model.interactorStyle3D.addGestureManipulator(gestureManipulator)
```

Can you change the commit message to
`feat(itkVtkView): add touch camera manipulator`

Reset the change to package-lock.json.

**Comment by idoRosen25** [comment]
@PaulHax i tried the location change you suggested but it doesn't work.
i found from my research the it is setting the `gestureManipulator` correctly only if placed in `transferFunctionManipulators.js`.

i changed the PR name to the one requested and also reverted the packge-lock file (only change is a new line which is added by my prettier formatting that i couldn't overwrite)

**Comment by PaulHax** [comment]
I opened a PR to your branch that move the gesture manipulator setup to place that makes a little more sense.  You could merge that on your branch.  Then to:

- [ ] Change the commit message to feat(itkVtkViewProxy): add touch camera manipulator
- [ ] Make this PR 1 commit with the above message
- [ ] remove the change to package-lock.json

use `git rebase -i`

**Comment by idoRosen25** [comment]
> I opened a PR to your branch that move the gesture manipulator setup to place that makes a little more sense. You could merge that on your branch. Then to:
> 
> * [ ]  Change the commit message to feat(itkVtkViewProxy): add touch camera manipulator
> * [ ]  Make this PR 1 commit with the above message
> * [ ]  remove the change to package-lock.json
> 
> use `git rebase -i`

can you send me a link to the PR you refer to? i cant seems to find it.

and can you better explain the steps to be made? im not sure i understand

**Comment by PaulHax** [comment]
Here is the PR:
https://github.com/idoRosen25/itk-vtk-viewer/pull/1

To modify the git history, use git's interactive rebase command.  The web will enplane better than me.  Goal is 1 commit with the formatted message and no modification to package-lock.json.

**Comment by idoRosen25** [comment]
I had been busy with other projects. however using @Jmennius help i opened a new PR with the changes as requested. 
this is the new PR: #626  
I'm closing this one without merge

**Pull request closed without merging**
