### PR TITLE
feat(GradientOpacitySlider): Adjust on a log scale

### PR DESCRIPTION
**Pull request by thewtex**
Gradient magnitudes for natural images are likely to have a power-law
distribution. To provide linear scale to the user adjusting gradient
opacity with the slider, make gradient opacity maximum and minimum steps
on a log scale.

### CODE REVIEW

**Comment by thewtex** [comment]
@martinken @jourdain would you like this pushed upstream into vtk.js?

**Comment by jourdain** [comment]
@martinken ?

**Comment by martinken** [comment]
Log works for me and makes sense. Didn't check the code too carefully but if it feels good on the GUI tests with a few datatsets then +1

**Pull request merged**
