### PR TITLE
fix(independentComponents): Require explicit RGB or RGBA pixelType

### PR DESCRIPTION
**Pull request by thewtex**
Do not make an implicit assumption so independentComponents can be
enabled via pixelType.

### CODE REVIEW

**Comment by oeway** [comment]
When passing ndarray from the ImJoy interface, since there is no way to explicitly set the pixelType, maybe we should support additional options for the `setImage` function?

**Comment by thewtex** [comment]
> When passing ndarray from the ImJoy interface, since there is no way to explicitly set the pixelType, maybe we should support additional options for the setImage function?

To prevent option creep/explosion on the viewer interface, can the object be converted, then the `pixelType` set?:

https://github.com/Kitware/itk-vtk-viewer/blob/94807c6385f1a4aec5d1e26d210292b56df13a62/src/utils.js#L11

**Comment by oeway** [comment]
Hi, I don't fully get, how would you do it?

**Comment by thewtex** [comment]
E.g.

```
itkImage = ndarrayToItkImage(ndarray)
itkImage.imageType.pixelType = 14
viewer.setImage(itkImage)
```

**Comment by oeway** [comment]
Aha, well, yes and no, for js plugins we can potentially do that, but it will be hard for Python plugins where we just want to call `viewer.setImage(numpy_array)`. We may not want to always import itk module, or have the ndarray2ItkImage() function defined in the plugin.

**Comment by thewtex** [comment]
Let's keep pushing forward Python plugins that provide the desired functionality.

Eventually in the config object, we will support an entire image configuration (data + complete config).

**Pull request merged**
