### PR TITLE
fix(zarrmultiscalespatialimage): support Zarr stores not ending in .zarr

### LINKED ISSUE #719: Support Zarr stores not ending in '.zarr'
Reading an OME-NGFF zarr [store](https://dl01.irc.ugent.be/spatial/proteomics/macsima_liver/ome_test/HumanLiverH35_3c_ome_microns.zarr/images/HumanLiverH35) without the usual `.zarr` suffix (probably not best practice but they exist) result in an [error](https://kitware.github.io/itk-vtk-viewer/app/?rotate=false&fileToLoad=https://dl01.irc.ugent.be/spatial/proteomics/macsima_liver/ome_test/HumanLiverH35_3c_ome_microns.zarr/images/HumanLiverH35):

```
message: "Could not find IO for: HumanLiverH35"
```

Can the reader logic be updated to support this?
Or can an additional URL parameter be added like [&use2D](https://kitware.github.io/itk-vtk-viewer/docs/viewer.html) to specify the reader?

### PR DESCRIPTION
**Pull request by berombau**
The isZarr regex was updated to support .zarr/image, besides just .zarr and DANDI /zarr/.

fix #719

### CODE REVIEW

**Comment by PaulHax** [comment]
Awesome!  One more little ask.  These tests are failing: 
https://github.com/Kitware/itk-vtk-viewer/blob/master/test/zarrTest.js#L43-L49

Perhaps we can add another bit to the regex to fix?

**Comment by PaulHax** [comment]
On second though, some of those failing tests are silly.  I made a couple tweeks to your PR here: 
https://github.com/berombau/itk-vtk-viewer/pull/1

Maybe we can incopreate then I'll merge and deploy.

**Comment by thewtex** [comment]
@berombau if it looks good, could you please merge @PaulHax 's pull request on your pull request? https://github.com/berombau/itk-vtk-viewer/pull/1

**Comment by berombau** [comment]
@PaulHax @thewtex is it good like this? Do I need to do anything else?

**Comment by PaulHax** [comment]
Much thanks.

**Pull request merged**
