### PR TITLE
Expose more viewer features via api

### PR DESCRIPTION
**Pull request by scottwittenburg**
Exposes `opacityGaussiansChanged` and `componentVisibilitiesChanged` events, as well as api to set/get those properties.

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@thewtex I thought I'd get this up so you can take a look while I'm exposing a few more of the things we talked about.  It required more re-working to expose the gaussians than I expected, mostly the `set` functionality, but it seems like it's working properly now, and there's a WIP commit demonstrating it.

**Comment by thewtex** [comment]
@scottwittenburg nice, thanks! The piecewise Gaussians will be awesome to have.

Are you working on `labelMapBlend` or `backgroundColor`? If not, I'll pick them up.

**Comment by scottwittenburg** [comment]
At the moment I'm exposing api for component visibilities.  That data structure contains the non-labelmap weights as well, which change with the labelmap blend, but I thought that should be separate api (or really just inferred from the labelmap blend).

But let me know if you agree.

**Comment by thewtex** [comment]
> At the moment I'm exposing api for component visibilities. That data structure contains the non-labelmap weights as well, which change with the labelmap blend, but I thought that should be separate api (or really just inferred from the labelmap blend).

> But let me know if you agree.

Yes, :+1:

**Pull request merged**
