### PR TITLE
feat(ImJoy): Support numpy array and 3D color image

### PR DESCRIPTION
**Pull request by oeway**
Fixes https://github.com/Kitware/itk-vtk-viewer/issues/344 and support displaying 3D color image.

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
@oeway sorry for the delayed reply -- look great, thanks!

**Comment by oeway** [comment]
Thanks! Just tested the released version, it also works in JupyterLab now!

Screenshot 2020-10-24 at 00 37 19

**Comment by thewtex** [comment]
@oeway love it!

**Pull request merged**
